image: node:4.2.2

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy


build:
  stage: build
  artifacts:
    paths:
      - build/
  script:
    - npm install
    - npm run build

pages:
  stage: deploy
  script:
    - mv build/ public/
  artifacts:
    untracked: true
    paths:
      - public/

